Internal Server Error: /customer/validate/bulk
Traceback (most recent call last):
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/rest_framework/response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/src/core/utils.py", line 102, in render
    return super().render(data, accepted_media_type, renderer_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Notification is not JSON serializable
"POST /customer/validate/bulk HTTP/1.1" 500 107436
Internal Server Error: /customer/validate/list/USER
Traceback (most recent call last):
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'core.utils.ApiResponse'>`
"GET /customer/validate/list/USER HTTP/1.1" 500 80566
Internal Server Error: /customer/validate/list/USER
Traceback (most recent call last):
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'core.utils.ApiResponse'>`
"GET /customer/validate/list/USER HTTP/1.1" 500 80566
Internal Server Error: /customer/list
Traceback (most recent call last):
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/rest_framework/response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/src/core/utils.py", line 119, in render
    return super().render(api_response.get_data(), accepted_media_type, renderer_context)
                          ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'get_data'
"GET /customer/list?page=1&page_size=20 HTTP/1.1" 500 17881
Internal Server Error: /customer/validate/list/USER
Traceback (most recent call last):
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'core.utils.ApiResponse'>`
"GET /customer/validate/list/USER HTTP/1.1" 500 80483
Internal Server Error: /customer/validate/list/USER
Traceback (most recent call last):
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'core.utils.ApiResponse'>`
"GET /customer/validate/list/USER HTTP/1.1" 500 80483
Internal Server Error: /customer/validate/list/USER
Traceback (most recent call last):
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'core.utils.ApiResponse'>`
"GET /customer/validate/list/USER HTTP/1.1" 500 80483
Internal Server Error: /customer/validate/list/USER
Traceback (most recent call last):
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'core.utils.ApiResponse'>`
"GET /customer/validate/list/USER HTTP/1.1" 500 80566
Internal Server Error: /customer/validate/list/USER
Traceback (most recent call last):
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'core.utils.ApiResponse'>`
"GET /customer/validate/list/USER HTTP/1.1" 500 80270
Internal Server Error: /customer/validate/list/USER
Traceback (most recent call last):
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'core.utils.ApiResponse'>`
"GET /customer/validate/list/USER HTTP/1.1" 500 80270
Internal Server Error: /customer/validate/list/USER
"GET /customer/validate/list/USER HTTP/1.1" 500 80
Internal Server Error: /customer/validate/list/USER
Traceback (most recent call last):
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oyejide/Documents/GitHub/ibedc-api-validation/venv/lib/python3.12/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'core.utils.ApiResponse'>`
"GET /customer/validate/list/USER HTTP/1.1" 500 78300
Internal Server Error: /customer/validate/list/USER
"GET /customer/validate/list/USER HTTP/1.1" 500 80
Internal Server Error: /customer/validate/list/USER
"GET /customer/validate/list/USER HTTP/1.1" 500 80
Internal Server Error: /customer/validate/list/USER
"GET /customer/validate/list/USER HTTP/1.1" 500 80
Internal Server Error: /customer/validate/list/USER
"GET /customer/validate/list/USER HTTP/1.1" 500 80
Internal Server Error: /customer/validate/list/USER
"GET /customer/validate/list/USER HTTP/1.1" 500 80
Internal Server Error: /customer/validate/list/USER
"GET /customer/validate/list/USER HTTP/1.1" 500 80
Internal Server Error: /customer/validate/list
"GET /customer/validate/list HTTP/1.1" 500 80
Internal Server Error: /customer/validate/batches/d72dad20-8be8-47d1-9777-fdf80a40d528/
"GET /customer/validate/batches/d72dad20-8be8-47d1-9777-fdf80a40d528/ HTTP/1.1" 500 80
Internal Server Error: /customer/validate/batches/d72dad20-8be8-47d1-9777-fdf80a40d528/
"GET /customer/validate/batches/d72dad20-8be8-47d1-9777-fdf80a40d528/ HTTP/1.1" 500 80
Internal Server Error: /customer/validate/batches/d72dad20-8be8-47d1-9777-fdf80a40d528/
"GET /customer/validate/batches/d72dad20-8be8-47d1-9777-fdf80a40d528/ HTTP/1.1" 500 80
Internal Server Error: /customer/validate/batches/d72dad20-8be8-47d1-9777-fdf80a40d528/
"GET /customer/validate/batches/d72dad20-8be8-47d1-9777-fdf80a40d528/ HTTP/1.1" 500 80
Internal Server Error: /customer/validate/batches/d72dad20-8be8-47d1-9777-fdf80a40d528/
"GET /customer/validate/batches/d72dad20-8be8-47d1-9777-fdf80a40d528/ HTTP/1.1" 500 80
Internal Server Error: /customer/validate/batches/d72dad20-8be8-47d1-9777-fdf80a40d528/
"GET /customer/validate/batches/d72dad20-8be8-47d1-9777-fdf80a40d528/ HTTP/1.1" 500 80
Internal Server Error: /customer/validate/batches/d72dad20-8be8-47d1-9777-fdf80a40d528/
"GET /customer/validate/batches/d72dad20-8be8-47d1-9777-fdf80a40d528/ HTTP/1.1" 500 80
